name: Upload CSV to S3

on:
  workflow_dispatch:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Deploy master branch"]
    types:
      - completed

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3'
      - name: Run Python script
        run:
          pip install boto3
          python pokemon_data_s3_upload.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#    - name: serverless deploy
#      uses: serverless/github-action@v3
#      with:
#        args: deploy




#look up how to add a step (above) in the process to run a python script
#create a step that runs pokemon_data_s3.py
#update pokemon_data_s3.py to use environment variable aws credentials instead of custom profile
#fix for csv
